# Generated by Django 4.2.1 on 2023-06-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_kg', models.FloatField()),
                ('date_visited', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=60)),
                ('img', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('specie_id', models.AutoField(primary_key=True, serialize=False)),
                ('species_name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vaccine_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinesAdministered',
            fields=[
                ('vaccines_administered_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petinfo')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonOfVisit',
            fields=[
                ('reason_of_visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pets.history')),
            ],
        ),
        migrations.AddField(
            model_name='petinfo',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.species'),
        ),
        migrations.AddField(
            model_name='history',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petinfo'),
        ),
    ]
